# Generated by Django 3.2.16 on 2023-08-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0016_alter_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='mycv',
            field=models.FileField(null=True, upload_to='pdfs/'),
        ),
    ]
