# Generated by Django 3.2.16 on 2023-08-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_alter_personalinformation_mycv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='mycv',
            field=models.URLField(blank=True, null=True),
        ),
    ]
