# Generated by Django 3.2.16 on 2023-08-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0018_auto_20230818_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinformation',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv'),
        ),
    ]
